/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as ReclamacionesRouteImport } from './routes/reclamaciones'
import { Route as MapasProvinciaRouteImport } from './routes/mapas-provincia'
import { Route as MapasAdminRouteImport } from './routes/mapas-admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FacturacionRouteImport } from './routes/facturacion'
import { Route as EpodRouteImport } from './routes/epod'
import { Route as DuplicadosRouteImport } from './routes/duplicados'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as Cd5RouteImport } from './routes/cd5'
import { Route as BorradoresRouteImport } from './routes/borradores'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportesPaquetesEnRiesgoRouteImport } from './routes/reportes_.paquetes-en-riesgo'
import { Route as ReportesFlowMeetingRouteImport } from './routes/reportes_.flow-meeting'
import { Route as RecTokenRouteImport } from './routes/rec.$token'
import { Route as ApiReportesIdRouteImport } from './routes/api/reportes.$id'
import { Route as ApiPublicCd5RouteImport } from './routes/api/public/cd5'

const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReclamacionesRoute = ReclamacionesRouteImport.update({
  id: '/reclamaciones',
  path: '/reclamaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const MapasProvinciaRoute = MapasProvinciaRouteImport.update({
  id: '/mapas-provincia',
  path: '/mapas-provincia',
  getParentRoute: () => rootRouteImport,
} as any)
const MapasAdminRoute = MapasAdminRouteImport.update({
  id: '/mapas-admin',
  path: '/mapas-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturacionRoute = FacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => rootRouteImport,
} as any)
const EpodRoute = EpodRouteImport.update({
  id: '/epod',
  path: '/epod',
  getParentRoute: () => rootRouteImport,
} as any)
const DuplicadosRoute = DuplicadosRouteImport.update({
  id: '/duplicados',
  path: '/duplicados',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const Cd5Route = Cd5RouteImport.update({
  id: '/cd5',
  path: '/cd5',
  getParentRoute: () => rootRouteImport,
} as any)
const BorradoresRoute = BorradoresRouteImport.update({
  id: '/borradores',
  path: '/borradores',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesPaquetesEnRiesgoRoute =
  ReportesPaquetesEnRiesgoRouteImport.update({
    id: '/reportes_/paquetes-en-riesgo',
    path: '/reportes/paquetes-en-riesgo',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReportesFlowMeetingRoute = ReportesFlowMeetingRouteImport.update({
  id: '/reportes_/flow-meeting',
  path: '/reportes/flow-meeting',
  getParentRoute: () => rootRouteImport,
} as any)
const RecTokenRoute = RecTokenRouteImport.update({
  id: '/rec/$token',
  path: '/rec/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReportesIdRoute = ApiReportesIdRouteImport.update({
  id: '/api/reportes/$id',
  path: '/api/reportes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCd5Route = ApiPublicCd5RouteImport.update({
  id: '/api/public/cd5',
  path: '/api/public/cd5',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/borradores': typeof BorradoresRoute
  '/cd5': typeof Cd5Route
  '/dashboard': typeof DashboardRoute
  '/duplicados': typeof DuplicadosRoute
  '/epod': typeof EpodRoute
  '/facturacion': typeof FacturacionRoute
  '/login': typeof LoginRoute
  '/mapas-admin': typeof MapasAdminRoute
  '/mapas-provincia': typeof MapasProvinciaRoute
  '/reclamaciones': typeof ReclamacionesRoute
  '/reportes': typeof ReportesRoute
  '/rec/$token': typeof RecTokenRoute
  '/reportes/flow-meeting': typeof ReportesFlowMeetingRoute
  '/reportes/paquetes-en-riesgo': typeof ReportesPaquetesEnRiesgoRoute
  '/api/public/cd5': typeof ApiPublicCd5Route
  '/api/reportes/$id': typeof ApiReportesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/borradores': typeof BorradoresRoute
  '/cd5': typeof Cd5Route
  '/dashboard': typeof DashboardRoute
  '/duplicados': typeof DuplicadosRoute
  '/epod': typeof EpodRoute
  '/facturacion': typeof FacturacionRoute
  '/login': typeof LoginRoute
  '/mapas-admin': typeof MapasAdminRoute
  '/mapas-provincia': typeof MapasProvinciaRoute
  '/reclamaciones': typeof ReclamacionesRoute
  '/reportes': typeof ReportesRoute
  '/rec/$token': typeof RecTokenRoute
  '/reportes/flow-meeting': typeof ReportesFlowMeetingRoute
  '/reportes/paquetes-en-riesgo': typeof ReportesPaquetesEnRiesgoRoute
  '/api/public/cd5': typeof ApiPublicCd5Route
  '/api/reportes/$id': typeof ApiReportesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/borradores': typeof BorradoresRoute
  '/cd5': typeof Cd5Route
  '/dashboard': typeof DashboardRoute
  '/duplicados': typeof DuplicadosRoute
  '/epod': typeof EpodRoute
  '/facturacion': typeof FacturacionRoute
  '/login': typeof LoginRoute
  '/mapas-admin': typeof MapasAdminRoute
  '/mapas-provincia': typeof MapasProvinciaRoute
  '/reclamaciones': typeof ReclamacionesRoute
  '/reportes': typeof ReportesRoute
  '/rec/$token': typeof RecTokenRoute
  '/reportes_/flow-meeting': typeof ReportesFlowMeetingRoute
  '/reportes_/paquetes-en-riesgo': typeof ReportesPaquetesEnRiesgoRoute
  '/api/public/cd5': typeof ApiPublicCd5Route
  '/api/reportes/$id': typeof ApiReportesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/borradores'
    | '/cd5'
    | '/dashboard'
    | '/duplicados'
    | '/epod'
    | '/facturacion'
    | '/login'
    | '/mapas-admin'
    | '/mapas-provincia'
    | '/reclamaciones'
    | '/reportes'
    | '/rec/$token'
    | '/reportes/flow-meeting'
    | '/reportes/paquetes-en-riesgo'
    | '/api/public/cd5'
    | '/api/reportes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/borradores'
    | '/cd5'
    | '/dashboard'
    | '/duplicados'
    | '/epod'
    | '/facturacion'
    | '/login'
    | '/mapas-admin'
    | '/mapas-provincia'
    | '/reclamaciones'
    | '/reportes'
    | '/rec/$token'
    | '/reportes/flow-meeting'
    | '/reportes/paquetes-en-riesgo'
    | '/api/public/cd5'
    | '/api/reportes/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/borradores'
    | '/cd5'
    | '/dashboard'
    | '/duplicados'
    | '/epod'
    | '/facturacion'
    | '/login'
    | '/mapas-admin'
    | '/mapas-provincia'
    | '/reclamaciones'
    | '/reportes'
    | '/rec/$token'
    | '/reportes_/flow-meeting'
    | '/reportes_/paquetes-en-riesgo'
    | '/api/public/cd5'
    | '/api/reportes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BorradoresRoute: typeof BorradoresRoute
  Cd5Route: typeof Cd5Route
  DashboardRoute: typeof DashboardRoute
  DuplicadosRoute: typeof DuplicadosRoute
  EpodRoute: typeof EpodRoute
  FacturacionRoute: typeof FacturacionRoute
  LoginRoute: typeof LoginRoute
  MapasAdminRoute: typeof MapasAdminRoute
  MapasProvinciaRoute: typeof MapasProvinciaRoute
  ReclamacionesRoute: typeof ReclamacionesRoute
  ReportesRoute: typeof ReportesRoute
  RecTokenRoute: typeof RecTokenRoute
  ReportesFlowMeetingRoute: typeof ReportesFlowMeetingRoute
  ReportesPaquetesEnRiesgoRoute: typeof ReportesPaquetesEnRiesgoRoute
  ApiPublicCd5Route: typeof ApiPublicCd5Route
  ApiReportesIdRoute: typeof ApiReportesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reclamaciones': {
      id: '/reclamaciones'
      path: '/reclamaciones'
      fullPath: '/reclamaciones'
      preLoaderRoute: typeof ReclamacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapas-provincia': {
      id: '/mapas-provincia'
      path: '/mapas-provincia'
      fullPath: '/mapas-provincia'
      preLoaderRoute: typeof MapasProvinciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapas-admin': {
      id: '/mapas-admin'
      path: '/mapas-admin'
      fullPath: '/mapas-admin'
      preLoaderRoute: typeof MapasAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturacion': {
      id: '/facturacion'
      path: '/facturacion'
      fullPath: '/facturacion'
      preLoaderRoute: typeof FacturacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epod': {
      id: '/epod'
      path: '/epod'
      fullPath: '/epod'
      preLoaderRoute: typeof EpodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duplicados': {
      id: '/duplicados'
      path: '/duplicados'
      fullPath: '/duplicados'
      preLoaderRoute: typeof DuplicadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cd5': {
      id: '/cd5'
      path: '/cd5'
      fullPath: '/cd5'
      preLoaderRoute: typeof Cd5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/borradores': {
      id: '/borradores'
      path: '/borradores'
      fullPath: '/borradores'
      preLoaderRoute: typeof BorradoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes_/paquetes-en-riesgo': {
      id: '/reportes_/paquetes-en-riesgo'
      path: '/reportes/paquetes-en-riesgo'
      fullPath: '/reportes/paquetes-en-riesgo'
      preLoaderRoute: typeof ReportesPaquetesEnRiesgoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes_/flow-meeting': {
      id: '/reportes_/flow-meeting'
      path: '/reportes/flow-meeting'
      fullPath: '/reportes/flow-meeting'
      preLoaderRoute: typeof ReportesFlowMeetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rec/$token': {
      id: '/rec/$token'
      path: '/rec/$token'
      fullPath: '/rec/$token'
      preLoaderRoute: typeof RecTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reportes/$id': {
      id: '/api/reportes/$id'
      path: '/api/reportes/$id'
      fullPath: '/api/reportes/$id'
      preLoaderRoute: typeof ApiReportesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cd5': {
      id: '/api/public/cd5'
      path: '/api/public/cd5'
      fullPath: '/api/public/cd5'
      preLoaderRoute: typeof ApiPublicCd5RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BorradoresRoute: BorradoresRoute,
  Cd5Route: Cd5Route,
  DashboardRoute: DashboardRoute,
  DuplicadosRoute: DuplicadosRoute,
  EpodRoute: EpodRoute,
  FacturacionRoute: FacturacionRoute,
  LoginRoute: LoginRoute,
  MapasAdminRoute: MapasAdminRoute,
  MapasProvinciaRoute: MapasProvinciaRoute,
  ReclamacionesRoute: ReclamacionesRoute,
  ReportesRoute: ReportesRoute,
  RecTokenRoute: RecTokenRoute,
  ReportesFlowMeetingRoute: ReportesFlowMeetingRoute,
  ReportesPaquetesEnRiesgoRoute: ReportesPaquetesEnRiesgoRoute,
  ApiPublicCd5Route: ApiPublicCd5Route,
  ApiReportesIdRoute: ApiReportesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
