/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as ReclamacionesRouteImport } from './routes/reclamaciones'
import { Route as MapasProvinciaRouteImport } from './routes/mapas-provincia'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FacturacionRouteImport } from './routes/facturacion'
import { Route as EpodRouteImport } from './routes/epod'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BorradoresRouteImport } from './routes/borradores'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecTokenRouteImport } from './routes/rec.$token'

const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReclamacionesRoute = ReclamacionesRouteImport.update({
  id: '/reclamaciones',
  path: '/reclamaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const MapasProvinciaRoute = MapasProvinciaRouteImport.update({
  id: '/mapas-provincia',
  path: '/mapas-provincia',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturacionRoute = FacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => rootRouteImport,
} as any)
const EpodRoute = EpodRouteImport.update({
  id: '/epod',
  path: '/epod',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BorradoresRoute = BorradoresRouteImport.update({
  id: '/borradores',
  path: '/borradores',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecTokenRoute = RecTokenRouteImport.update({
  id: '/rec/$token',
  path: '/rec/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/borradores': typeof BorradoresRoute
  '/dashboard': typeof DashboardRoute
  '/epod': typeof EpodRoute
  '/facturacion': typeof FacturacionRoute
  '/login': typeof LoginRoute
  '/mapas-provincia': typeof MapasProvinciaRoute
  '/reclamaciones': typeof ReclamacionesRoute
  '/reportes': typeof ReportesRoute
  '/rec/$token': typeof RecTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/borradores': typeof BorradoresRoute
  '/dashboard': typeof DashboardRoute
  '/epod': typeof EpodRoute
  '/facturacion': typeof FacturacionRoute
  '/login': typeof LoginRoute
  '/mapas-provincia': typeof MapasProvinciaRoute
  '/reclamaciones': typeof ReclamacionesRoute
  '/reportes': typeof ReportesRoute
  '/rec/$token': typeof RecTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/borradores': typeof BorradoresRoute
  '/dashboard': typeof DashboardRoute
  '/epod': typeof EpodRoute
  '/facturacion': typeof FacturacionRoute
  '/login': typeof LoginRoute
  '/mapas-provincia': typeof MapasProvinciaRoute
  '/reclamaciones': typeof ReclamacionesRoute
  '/reportes': typeof ReportesRoute
  '/rec/$token': typeof RecTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/borradores'
    | '/dashboard'
    | '/epod'
    | '/facturacion'
    | '/login'
    | '/mapas-provincia'
    | '/reclamaciones'
    | '/reportes'
    | '/rec/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/borradores'
    | '/dashboard'
    | '/epod'
    | '/facturacion'
    | '/login'
    | '/mapas-provincia'
    | '/reclamaciones'
    | '/reportes'
    | '/rec/$token'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/borradores'
    | '/dashboard'
    | '/epod'
    | '/facturacion'
    | '/login'
    | '/mapas-provincia'
    | '/reclamaciones'
    | '/reportes'
    | '/rec/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BorradoresRoute: typeof BorradoresRoute
  DashboardRoute: typeof DashboardRoute
  EpodRoute: typeof EpodRoute
  FacturacionRoute: typeof FacturacionRoute
  LoginRoute: typeof LoginRoute
  MapasProvinciaRoute: typeof MapasProvinciaRoute
  ReclamacionesRoute: typeof ReclamacionesRoute
  ReportesRoute: typeof ReportesRoute
  RecTokenRoute: typeof RecTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reclamaciones': {
      id: '/reclamaciones'
      path: '/reclamaciones'
      fullPath: '/reclamaciones'
      preLoaderRoute: typeof ReclamacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapas-provincia': {
      id: '/mapas-provincia'
      path: '/mapas-provincia'
      fullPath: '/mapas-provincia'
      preLoaderRoute: typeof MapasProvinciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturacion': {
      id: '/facturacion'
      path: '/facturacion'
      fullPath: '/facturacion'
      preLoaderRoute: typeof FacturacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epod': {
      id: '/epod'
      path: '/epod'
      fullPath: '/epod'
      preLoaderRoute: typeof EpodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/borradores': {
      id: '/borradores'
      path: '/borradores'
      fullPath: '/borradores'
      preLoaderRoute: typeof BorradoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rec/$token': {
      id: '/rec/$token'
      path: '/rec/$token'
      fullPath: '/rec/$token'
      preLoaderRoute: typeof RecTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BorradoresRoute: BorradoresRoute,
  DashboardRoute: DashboardRoute,
  EpodRoute: EpodRoute,
  FacturacionRoute: FacturacionRoute,
  LoginRoute: LoginRoute,
  MapasProvinciaRoute: MapasProvinciaRoute,
  ReclamacionesRoute: ReclamacionesRoute,
  ReportesRoute: ReportesRoute,
  RecTokenRoute: RecTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
